### ISSUE TITLE
for pde code running 

### ISSUE THREAD

**Issue by zgyd97** [tianjuxue/AmorFEA#1]
I'm trying to run the dolfin demo code in pde, but there are some errors reported. I have already installed mshr by command"conda install mshr". 
  The error reads,ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable" Is there any solution ,thanks for help.

**Comment by tianjuxue** [comment]
The issue can be solved by specifying the versions of `fenics` and `mshr`. Suppose your conda environment is named as `fenics_env`, activate this environment and create a file named `environment.yml`. Then run
`conda env update -f environment.yml`
This should resolve the issue.

The contents in `environment.yml ` could be
```
name: fenics_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib<=2.2.3
  - scipy<=1.1
  - jupyterlab>=1.2
  - fenics=2019
  - sympy=1.1.1
  - mshr=2019.1.0=py37hf9f41d3_3
  - petsc

```

**Comment by Navid-visual** [comment]
I get the same error:
ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable"
I tried the suggested solution but it does not solve the issue for me. Do you have any other suggestions?

**Comment by Navid-visual** [comment]
This has worked for me:
https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062/5

I did the same as Hwan but to avoid confusing versions I created a new environment which I called fenics2018 with the 2018 version of fenics and mshr
since I work with jupyter notebook I did the following

**conda create -n fenics2018 -c conda-forge python=3.7 ipython jupyter fenics=2018 mshr=2018**
